apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-kubernetes
  template:
    metadata:
      labels:
        app: app-kubernetes
    spec:
      containers:
        - name: app-container
          image: natan085/api-hexagonal:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
